//
// Created by fz on 8/28/20.
//

#ifndef TFLITE_DEMO_APP_SRC_MAIN_CPP_NEWSTRINGUTF2_H
#define TFLITE_DEMO_APP_SRC_MAIN_CPP_NEWSTRINGUTF2_H

class NewStringUTF2 {

};

#endif //TFLITE_DEMO_APP_SRC_MAIN_CPP_NEWSTRINGUTF2_H
